// import { Inter } from "next/font/google";
import "./globals.css";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/image/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/image/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/image/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/image/favicon-16x16.png"
        />
        <link rel="manifest" href="/image/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#00b5d2" />
        <meta name="theme-color" content="#00b5d2" />
        <link rel="preload" href="/LoliPop.ttf" as="font" />
        <link rel="preload" href="/images/quiz.png" as="image" />
        <link rel="preload" href="/images/login.png" as="image" />
      </head>
      <body className="">{children}</body>
    </html>
  );
}
