const activity = [
  {
    id: 1,
    detail: "Computer Applications Quiz 3",
    coins: "60",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 2,
    detail: "Computer Applications Quiz 3",
    coins: "48",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 3,
    detail: "Computer Applications Quiz 3",
    coins: "44",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 4,
    detail: "Computer Applications Quiz 3",
    coins: "20",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 5,
    detail: "Computer Applications Quiz 3",
    coins: "56",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 6,
    detail: "Computer Applications Quiz 3",
    coins: "52",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 7,
    detail: "Computer Applications Quiz 3",
    coins: "36",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 8,
    detail: "Computer Applications Quiz 3",
    coins: "40",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 9,
    detail: "Computer Applications Quiz 3",
    coins: "32",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 10,
    detail: "Computer Applications Quiz 3",
    coins: "28",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 11,
    detail: "Computer Applications Quiz 3",
    coins: "20",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 12,
    detail: "Computer Applications Quiz 3",
    coins: "16",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 13,
    detail: "Computer Applications Quiz 3",
    coins: "44",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 14,
    detail: "Computer Applications Quiz 3",
    coins: "8",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 15,
    detail: "Computer Applications Quiz 3",
    coins: "28",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 16,
    detail: "Computer Applications Quiz 3",
    coins: "52",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 17,
    detail: "Computer Applications Quiz 3",
    coins: "36",
    date: "20 sep , 2023",
    path: "/review",
  },
  {
    id: 18,
    detail: "Computer Applications Quiz 3",
    coins: "12",
    date: "20 sep , 2023",
    path: "/review",
  },
];

export default activity;
